apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dsset
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      name: mytemp
      labels:
        app: myapp
    spec:
      containers:
        - name: mydscont
          image: amazon/cloudwatch-agent
          ports:
            - name: myport
              containerPort: 80