apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    app: myapp
    env: devops
spec:
  containers:
    - name: mycontainer
      image: nginx:latest
      ports:
        - name: nginx-port
          containerPort: 80
