apiVersion: v1
kind: gitPod
metadata:
  name: mypod
  labels:
    app: myapp
    env: devops
...
---
spec:
  containers:
    - name: mycontainer
      image: nginx:latest
      ports:
        - name: nginx-port
          containerPort: 80
