apiVersion: v1
kind: Pod
metadata:
  name: mypodofci
  labels: 
    app: myapp
spec:
  containers:
    - name: mycont
      image: nginx:latest
      ports:
        - name: myport
          containerPort: 80
...
---
apiVersion: v1
kind: Service
metadata:
  name: myci
  labels:
    app: myapp
spec:
  type: ClusterIP
  selector:
    app: myapp
  ports:
    - name: myport
      protocol: TCP
      targetPort: 80
      port: 80
