---                                                                                                     
apiVersion: v1
kind: Namespace
metadata:
  name: test
  labels:
    app: myapp
---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
  namespace: test
  labels:
    app: myapp
spec:
  containers:
    - name: mycont
      image: nginx:latest
      ports: 
        - name: myport
          containerPort: 80
    