apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels: 
    app: myapp
spec:
  containers:
    - name: mycont
      image: nginx:latest
      ports:
        - name: myport
          containerPort: 80
