apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  labels:
    app: myapp
spec:
  resources:
    requests:
      storage: 5Gi
  storageClassName: standered
  accessModes:
    - ReadWriteOnce    
