apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  labels:
    app: myapp  
    env: devops
type: opaque
data:
  MYSQL_USER: dXNlcg==
  MYSQL_PASSWORD: cGFzc3dvcmQ=
  MYSQL_ROOT__PASSWORD: cm9vdA==

