apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    app: myapp
spec:
  volumes:
    - name: my-volume
      persistentVolumeClaim:
        claimName: my-pvc
  containers:
    - name: mycont
      image: nginx:latest
      ports:
        - name: myport
          containerPort: 80
      volumeMounts:
        - name: my-volume
          mountPath: /usr/share/ngix/html/