apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  labels:
    app: myapp
  namespace: myspace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my app
  template: 
    metadata:
      name: mytemp
      labels:
        app: myapp
    spec:
      containers:
        - name: mycont
          image: nginx:latest
          ports:
            - name: myport
              containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "64M"