apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: myhpa
  labels: 
    app: myapp
  namespace: myspace
spec:
  scaleTargetRef:
    apiVersion: app/v1
    kind: Deployment
    name: my_deployment
  minreplicas: 1
  maxreplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 40
      
  