apiVersion: v1
kind: Service
metadata: 
  name: my_svc
  labels:
    app: myapp
  namespace: myspace
spec:
  containers:
    type: ClusterIP
    selector:
      app: myapp
    ports:
      - name: myports
        protocol: TCP
        port: 80
        targetPort: 80
    
